<?php

use ChrisMallory\PromoBanner\ViewModel\Header\PromoBanner;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var PromoBanner $viewModel */
$viewModel = $block->getData('viewModel');
$promoLink = $viewModel->getPromoLink();
?>
<?php if ($viewModel->isEnabled()): ?>
    <?php if ($viewModel->isUseCustomStyles()): ?>
        <?php $customStyles = $viewModel->getCustomStyles() ?>
        <style>
        <?php if ($customStyles['background']): ?>
        div.promo-banner-wrapper { background: <?= $block->escapeCss($customStyles['background']) ?> }
        <?php endif; ?>
        <?php if ($customStyles['font_size'] || $customStyles['font_weight'] || $customStyles['color']): ?>
        div.promo-banner-wrapper div.promo-banner-message {
            <?php if ($color = $block->escapeCss($customStyles['color'])): ?>
            color: <?= $block->escapeCss($color) ?>;
            <?php endif; ?>
            <?php if ($fontSize = $customStyles['font_size']): ?>
            font-size: <?= $block->escapeCss($fontSize) ?>;
            <?php endif; ?>
            <?php if ($fontWeight = $customStyles['font_weight']): ?>
            font-weight: <?= $block->escapeCss($fontWeight) ?>;
            <?php endif; ?>
        }
        <?php endif; ?>
        </style>
    <?php endif; ?>
    <div class="promo-banner-wrapper">
        <div class="promo-banner-message">
            <?php if ($promoLink): ?>
            <a href="<?= $block->escapeUrl($promoLink) ?>">
            <?php endif; ?>
            <span><?= $block->escapeHtml($viewModel->getPromoText()) ?></span>
            <?php if ($promoLink): ?>
            </a>
            <?php endif; ?>
        </div>
    </div>
<?php endif ?>
